# Generated by Django 3.1.5 on 2021-01-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('url', models.URLField(blank=True, unique=True)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
